#!/usr/bin/env bash
set -euo pipefail

gcloud auth login

gcloud config set project gen-lang-client-0922281168

set -a
source .env
set +a

gcloud run deploy "$SERVICE_NAME" \
  --source . \
  --region "$GOOGLE_CLOUD_LOCATION" \
  --project "$GOOGLE_CLOUD_PROJECT" \
  --allow-unauthenticated \
  --port 8080 \
  --set-env-vars="
CLICKUP_API_KEY=$CLICKUP_API_KEY,\
CLICKUP_CLIENT_ID=$CLICKUP_CLIENT_ID,\
CLICKUP_CLIENT_SECRET=$CLICKUP_CLIENT_SECRET,\
CLICKUP_ACCESS_TOKEN=$CLICKUP_ACCESS_TOKEN,\
OPENAI_API_KEY=$OPENAI_API_KEY,\
SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN,\
GOOGLE_API_KEY=$GOOGLE_API_KEY,\
GOOGLE_GENAI_USE_VERTEXAI=$GOOGLE_GENAI_USE_VERTEXAI,\
GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT,\
GOOGLE_CLOUD_LOCATION=$GOOGLE_CLOUD_LOCATION,\
AGENT_PATH=$AGENT_PATH,\
SERVICE_NAME=$SERVICE_NAME,\
APP_NAME=$APP_NAME,\
SUPABASE_URL=$SUPABASE_URL,\
SUPABASE_KEY=$SUPABASE_KEY,\
SUPABASE_DB_URL=$SUPABASE_DB_URL"